library(plyr)
library(dplyr)
library(ggmap)
library(ggplot2)
library(readr)
library(stringr)
 
source('load-data.r')
source('visualize-month.r')
source('visualize-day.r')
source('visualize-categories.r')
source('visualize-weekday.r')
source('visualize-hours.r')
source('visualize-map.r')
source('visualize-status.r')
source('visualize-pddistrict.r')
source('visualize-address.r')
